export const getFlagUrl = (teamName) => {
  const mapping = {
    'Algeria': 'dz',
    'Argentina': 'ar',
    'Australia': 'au',
    'Austria': 'at',
    'Belgium': 'be',
    'Bosnia': 'ba',
    'Brazil': 'br',
    'Canada': 'ca',
    'Chile': 'cl',
    'Colombia': 'co',
    'Croatia': 'hr',
    'Czechia': 'cz',
    'Denmark': 'dk',
    'DR Congo': 'cd',
    'Ecuador': 'ec',
    'Egypt': 'eg',
    'England': 'gb-eng',
    'France': 'fr',
    'Germany': 'de',
    'Ghana': 'gh',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Ivory Coast': 'ci',
    'Japan': 'jp',
    'Mexico': 'mx',
    'Morocco': 'ma',
    'Netherlands': 'nl',
    'New Zealand': 'nz',
    'Norway': 'no',
    'Panama': 'pa',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Portugal': 'pt',
    'Saudi Arabia': 'sa',
    'Scotland': 'gb-sct',
    'Senegal': 'sn',
    'South Africa': 'za',
    'South Korea': 'kr',
    'Spain': 'es',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Tunisia': 'tn',
    'Turkey': 'tr',
    'Ukraine': 'ua',
    'Uruguay': 'uy',
    'USA': 'us',
    'Uzbekistan': 'uz',
    'Venezuela': 've'
  };

  const code = mapping[teamName] || 'un';
  return `https://flagcdn.com/w80/${code.toLowerCase()}.png`;
};
